package blueshared


type Get10Options struct {
  NoAttack               bool
  NoAttackWithoutDefense bool
  SetsAvailable          []int
  ForbiddenCards         []int
}

type Card struct {
  Id   int
  Set  int
  Name string
  Cost string
  Type string
}

var AllCards []Card
 
func init() { 
  AllCards = []Card{
    Card{Id:0, Set: 0, Name: "Cellar", Type: "Action", Cost:"$2"},
    Card{Id:1, Set: 0, Name: "Chapel", Type: "Action", Cost:"$2"},
    Card{Id:2, Set: 0, Name: "Moat", Type: "Action &#8211; Reaction", Cost:"$2"},
    Card{Id:3, Set: 0, Name: "Chancellor",  Type: "Action", Cost:"$3"},
    Card{Id:4, Set: 0, Name: "Village", Type: "Action", Cost:"$3"},
    Card{Id:5, Set: 0, Name: "Woodcutter", Type: "Action", Cost:"$3"},
    Card{Id:6, Set: 0, Name: "Workshop", Type: "Action", Cost:"$3"},
    Card{Id:7, Set: 0, Name: "Bureaucrat", Type: "Action &#8211; Attack", Cost:"$4"},
    Card{Id:8, Set: 0, Name: "Feast", Type: "Action", Cost:"$4"},
    Card{Id:9, Set: 0, Name: "Gardens", Type: "Victory", Cost:"$4"},
    Card{Id:10, Set: 0, Name: "Militia", Type: "Action &#8211; Attack", Cost:"$4"},
    Card{Id:11, Set: 0, Name: "Moneylender", Type: "Action", Cost:"$4"},
    Card{Id:12, Set: 0, Name: "Remodel", Type: "Action", Cost:"$4"},
    Card{Id:13, Set: 0, Name: "Smithy", Type: "Action", Cost:"$4"},
    Card{Id:14, Set: 0, Name: "Spy", Type: "Action &#8211; Attack", Cost:"$4"},
    Card{Id:15, Set: 0, Name: "Thief", Type: "Action &#8211; Attack", Cost:"$4"},
    Card{Id:16, Set: 0, Name: "Throne Room", Type: "Action", Cost:"$4"},
    Card{Id:17, Set: 0, Name: "Council Room", Type: "Action", Cost:"$5"},
    Card{Id:18, Set: 0, Name: "Festival", Type: "Action", Cost:"$5"},
    Card{Id:19, Set: 0, Name: "Laboratory", Type: "Action", Cost:"$5"},
    Card{Id:20, Set: 0, Name: "Library", Type: "Action", Cost:"$5"},
    Card{Id:21, Set: 0, Name: "Market", Type: "Action", Cost:"$5"},
    Card{Id:22, Set: 0, Name: "Mine", Type: "Action", Cost:"$5"},
    Card{Id:23, Set: 0, Name: "Witch", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:24, Set: 0, Name: "Adventurer", Type: "Action", Cost:"$6"},
    Card{Id:25, Set: 1, Name: "Courtyard", Type: "Action", Cost:"$2"},
    Card{Id:26, Set: 1, Name: "Pawn", Type: "Action", Cost:"$2"},
    Card{Id:27, Set: 1, Name: "Secret Chamber", Type: "Action &#8211; Reaction", Cost:"$2"},
    Card{Id:28, Set: 1, Name: "Great Hall", Type: "Action &#8211; Victory", Cost:"$3"},
    Card{Id:29, Set: 1, Name: "Masquerade", Type: "Action", Cost:"$3"},
    Card{Id:30, Set: 1, Name: "Shanty Town", Type: "Action", Cost:"$3"},
    Card{Id:31, Set: 1, Name: "Steward", Type: "Action", Cost:"$3"},
    Card{Id:32, Set: 1, Name: "Swindler", Type: "Action &#8211; Attack", Cost:"$3"},
    Card{Id:33, Set: 1, Name: "Wishing Well", Type: "Action", Cost:"$3"},
    Card{Id:34, Set: 1, Name: "Baron", Type: "Action", Cost:"$4"},
    Card{Id:35, Set: 1, Name: "Bridge", Type: "Action", Cost:"$4"},
    Card{Id:36, Set: 1, Name: "Conspirator", Type: "Action", Cost:"$4"},
    Card{Id:37, Set: 1, Name: "Coppersmith", Type: "Action", Cost:"$4"},
    Card{Id:38, Set: 1, Name: "Ironworks", Type: "Action", Cost:"$4"},
    Card{Id:39, Set: 1, Name: "Mining Village", Type: "Action", Cost:"$4"},
    Card{Id:40, Set: 1, Name: "Scout", Type: "Action", Cost:"$4"},
    Card{Id:41, Set: 1, Name: "Duke", Type: "Victory", Cost:"$5"},
    Card{Id:42, Set: 1, Name: "Minion", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:43, Set: 1, Name: "Saboteur", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:44, Set: 1, Name: "Torturer", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:45, Set: 1, Name: "Trading Post", Type: "Action", Cost:"$5"},
    Card{Id:46, Set: 1, Name: "Tribute", Type: "Action", Cost:"$5"},
    Card{Id:47, Set: 1, Name: "Upgrade", Type: "Action", Cost:"$5"},
    Card{Id:48, Set: 1, Name: "Harem", Type: "Treasure &#8211; Victory", Cost:"$6"},
    Card{Id:49, Set: 1, Name: "Nobles", Type: "Action &#8211; Victory", Cost:"$6"},
    Card{Id:50, Set: 2, Name: "Embargo", Type: "Action", Cost:"$2"},
    Card{Id:51, Set: 2, Name: "Haven", Type: "Action &#8211; Duration", Cost:"$2"},
    Card{Id:52, Set: 2, Name: "Lighthouse", Type: "Action &#8211; Duration", Cost:"$2"},
    Card{Id:53, Set: 2, Name: "Native Village", Type: "Action", Cost:"$2"},
    Card{Id:54, Set: 2, Name: "Pearl Diver", Type: "Action", Cost:"$2"},
    Card{Id:55, Set: 2, Name: "Ambassador (part II)", Type: "Action &#8211; Attack", Cost:"$3"},
    Card{Id:56, Set: 2, Name: "Fishing Village", Type: "Action &#8211; Duration", Cost:"$3"},
    Card{Id:57, Set: 2, Name: "Lookout", Type: "Action", Cost:"$3"},
    Card{Id:58, Set: 2, Name: "Smugglers", Type: "Action", Cost:"$3"},
    Card{Id:59, Set: 2, Name: "Warehouse", Type: "Action", Cost:"$3"},
    Card{Id:60, Set: 2, Name: "Caravan", Type: "Action &#8211; Duration", Cost:"$4"},
    Card{Id:61, Set: 2, Name: "Cutpurse", Type: "Action &#8211; Attack", Cost:"$4"},
    Card{Id:62, Set: 2, Name: "Island", Type: "Action &#8211; Victory", Cost:"$4"},
    Card{Id:63, Set: 2, Name: "Navigator", Type: "Action", Cost:"$4"},
    Card{Id:64, Set: 2, Name: "Pirate Ship", Type: "Action &#8211; Attack", Cost:"$4"},
    Card{Id:65, Set: 2, Name: "Salvager", Type: "Action", Cost:"$4"},
    Card{Id:66, Set: 2, Name: "Sea Hag", Type: "Action &#8211; Attack", Cost:"$4"},
    Card{Id:67, Set: 2, Name: "Treasure Map", Type: "Action", Cost:"$4"},
    Card{Id:68, Set: 2, Name: "Bazaar", Type: "Action", Cost:"$5"},
    Card{Id:69, Set: 2, Name: "Explorer", Type: "Action", Cost:"$5"},
    Card{Id:70, Set: 2, Name: "Ghost Ship", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:71, Set: 2, Name: "Merchant Ship", Type: "Action &#8211; Duration", Cost:"$5"},
    Card{Id:72, Set: 2, Name: "Outpost", Type: "Action &#8211; Duration", Cost:"$5"},
    Card{Id:73, Set: 2, Name: "Tactician", Type: "Action &#8211; Duration", Cost:"$5"},
    Card{Id:74, Set: 2, Name: "Treasury", Type: "Action", Cost:"$5"},
    Card{Id:75, Set: 2, Name: "Wharf", Type: "Action &#8211; Duration", Cost:"$5"},
    Card{Id:76, Set: 3, Name: "Herbalist", Type: "Action", Cost:"$2"},
    Card{Id:77, Set: 3, Name: "Potion", Type: "Treasure", Cost:"$4"},
    Card{Id:78, Set: 3, Name: "Apprentice", Type: "Action", Cost:"$5"},
    Card{Id:79, Set: 3, Name: "Transmute", Type: "Action", Cost:"$0◉"},
    Card{Id:80, Set: 3, Name: "Vineyard", Type: "Victory", Cost:"$0◉"},
    Card{Id:81, Set: 3, Name: "Apothecary", Type: "Action", Cost:"$2◉"},
    Card{Id:82, Set: 3, Name: "Scrying Pool", Type: "Action &#8211; Attack", Cost:"$2◉"},
    Card{Id:83, Set: 3, Name: "University", Type: "Action", Cost:"$2◉"},
    Card{Id:84, Set: 3, Name: "Alchemist", Type: "Action", Cost:"$3◉"},
    Card{Id:85, Set: 3, Name: "Familiar", Type: "Action &#8211; Attack", Cost:"$3◉"},
    Card{Id:86, Set: 3, Name: "Philosopher&#8217;s Stone", Type: "Treasure", Cost:"$3◉"},
    Card{Id:87, Set: 3, Name: "Golem", Type: "Action", Cost:"$4◉"},
    Card{Id:88, Set: 3, Name: "Possession", Type: "Action", Cost:"$6◉"},
    Card{Id:89, Set: 4, Name: "Loan", Type: "Treasure", Cost:"$3"},
    Card{Id:90, Set: 4, Name: "Trade Route", Type: "Action", Cost:"$3"},
    Card{Id:91, Set: 4, Name: "Watchtower", Type: "Action &#8211; Reaction", Cost:"$3"},
    Card{Id:92, Set: 4, Name: "Bishop", Type: "Action", Cost:"$4"},
    Card{Id:93, Set: 4, Name: "Monument", Type: "Action", Cost:"$4"},
    Card{Id:94, Set: 4, Name: "Quarry", Type: "Treasure", Cost:"$4"},
    Card{Id:95, Set: 4, Name: "Talisman", Type: "Treasure", Cost:"$4"},
    Card{Id:96, Set: 4, Name: "Worker&#8217;s Village", Type: "Action", Cost:"$4"},
    Card{Id:97, Set: 4, Name: "City", Type: "Action", Cost:"$5"},
    Card{Id:98, Set: 4, Name: "Contraband", Type: "Treasure", Cost:"$5"},
    Card{Id:99, Set: 4, Name: "Counting House", Type: "Action", Cost:"$5"},
    Card{Id:100, Set: 4, Name: "Mint", Type: "Action", Cost:"$5"},
    Card{Id:101, Set: 4, Name: "Mountebank", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:102, Set: 4, Name: "Rabble", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:103, Set: 4, Name: "Royal Seal", Type: "Treasure", Cost:"$5"},
    Card{Id:104, Set: 4, Name: "Vault", Type: "Action", Cost:"$5"},
    Card{Id:105, Set: 4, Name: "Venture", Type: "Treasure", Cost:"$5"},
    Card{Id:106, Set: 4, Name: "Goons", Type: "Action &#8211; Attack", Cost:"$6"},
    Card{Id:107, Set: 4, Name: "Grand Market", Type: "Action", Cost:"$6"},
    Card{Id:108, Set: 4, Name: "Hoard", Type: "Treasure", Cost:"$6"},
    Card{Id:109, Set: 4, Name: "Bank", Type: "Treasure", Cost:"$7"},
    Card{Id:110, Set: 4, Name: "Expand", Type: "Action", Cost:"$7"},
    Card{Id:111, Set: 4, Name: "Forge", Type: "Action", Cost:"$7"},
    Card{Id:112, Set: 4, Name: "King&#8217;s Court", Type: "Action", Cost:"$7"},
    Card{Id:113, Set: 4, Name: "Peddler", Type: "Action", Cost:"$8*"},
    Card{Id:114, Set: 4, Name: "Platinum", Type: "Treasure", Cost:"$9"},
    Card{Id:115, Set: 4, Name: "Colony", Type: "Victory", Cost:"$11"},
    Card{Id:116, Set: 5, Name: "Hamlet", Type: "Action", Cost:"$2"},
    Card{Id:117, Set: 5, Name: "Fortune Teller", Type: "Action &#8211; Attack", Cost:"$3"},
    Card{Id:118, Set: 5, Name: "Menagerie", Type: "Action", Cost:"$3"},
    Card{Id:119, Set: 5, Name: "Farming Village", Type: "Action", Cost:"$4"},
    Card{Id:120, Set: 5, Name: "Horse Traders", Type: "Action &#8211; Reaction", Cost:"$4"},
    Card{Id:121, Set: 5, Name: "Remake", Type: "Action", Cost:"$4"},
    Card{Id:122, Set: 5, Name: "Tournament", Type: "Action", Cost:"$4"},
    Card{Id:123, Set: 5, Name: "Young Witch", Type: "Action &#8211; Attack", Cost:"$4"},
    Card{Id:124, Set: 5, Name: "Harvest", Type: "Action", Cost:"$5"},
    Card{Id:125, Set: 5, Name: "Horn of Plenty", Type: "Treasure", Cost:"$5"},
    Card{Id:126, Set: 5, Name: "Hunting Party", Type: "Action", Cost:"$5"},
    Card{Id:127, Set: 5, Name: "Jester", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:128, Set: 5, Name: "Fairgrounds", Type: "Victory", Cost:"$6"},
    Card{Id:129, Set: 5, Name: "Bag of Gold", Type: "Action &#8211; Prize", Cost:"$0*"},
    Card{Id:130, Set: 5, Name: "Diadem", Type: "Treasure &#8211; Prize", Cost:"$0*"},
    Card{Id:131, Set: 5, Name: "Followers", Type: "Action &#8211; Attack &#8211; Prize", Cost:"$0*"},
    Card{Id:132, Set: 5, Name: "Princess", Type: "Action &#8211; Prize", Cost:"$0*"},
    Card{Id:133, Set: 5, Name: "Trusty Steed", Type: "Action &#8211; Prize", Cost:"$0*"},
    Card{Id:134, Set: 6, Name: "Crossroads", Type: "Action", Cost:"$2"},
    Card{Id:135, Set: 6, Name: "Duchess", Type: "Action", Cost:"$2"},
    Card{Id:136, Set: 6, Name: "Fool&#8217;s Gold", Type: "Treasure &#8211; Reaction", Cost:"$2"},
    Card{Id:137, Set: 6, Name: "Develop", Type: "Action", Cost:"$3"},
    Card{Id:138, Set: 6, Name: "Oasis", Type: "Action", Cost:"$3"},
    Card{Id:139, Set: 6, Name: "Oracle", Type: "Action &#8211; Attack", Cost:"$3"},
    Card{Id:140, Set: 6, Name: "Scheme", Type: "Action", Cost:"$3"},
    Card{Id:141, Set: 6, Name: "Tunnel", Type: "Victory &#8211; Reaction", Cost:"$3"},
    Card{Id:142, Set: 6, Name: "Jack of All Trades", Type: "Action", Cost:"$4"},
    Card{Id:143, Set: 6, Name: "Noble Brigand", Type: "Action &#8211; Attack", Cost:"$4"},
    Card{Id:144, Set: 6, Name: "Nomad Camp<br />", Type: "Action", Cost:"$4"},
    Card{Id:145, Set: 6, Name: "Silk Road", Type: "Victory", Cost:"$4"},
    Card{Id:146, Set: 6, Name: "Spice Merchant", Type: "Action", Cost:"$4"},
    Card{Id:147, Set: 6, Name: "Trader", Type: "Action &#8211; Reaction", Cost:"$4"},
    Card{Id:148, Set: 6, Name: "Cache", Type: "Treasure", Cost:"$5"},
    Card{Id:149, Set: 6, Name: "Cartographer", Type: "Action", Cost:"$5"},
    Card{Id:150, Set: 6, Name: "Embassy", Type: "Action", Cost:"$5"},
    Card{Id:151, Set: 6, Name: "Haggler", Type: "Action", Cost:"$5"},
    Card{Id:152, Set: 6, Name: "Highway", Type: "Action", Cost:"$5"},
    Card{Id:153, Set: 6, Name: "Ill-Gotten Gains", Type: "Treasure", Cost:"$5"},
    Card{Id:154, Set: 6, Name: "Inn", Type: "Action", Cost:"$5"},
    Card{Id:155, Set: 6, Name: "Mandarin", Type: "Action", Cost:"$5"},
    Card{Id:156, Set: 6, Name: "Margrave", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:157, Set: 6, Name: "Stables", Type: "Action", Cost:"$5"},
    Card{Id:158, Set: 6, Name: "Border Village", Type: "Action", Cost:"$6"},
    Card{Id:159, Set: 6, Name: "Farmland", Type: "Victory", Cost:"$6"},
    Card{Id:160, Set: 7, Name: "Madman", Type: "Action", Cost:"$0*"},
    Card{Id:161, Set: 7, Name: "Mercenary", Type: "Action &#8211; Attack", Cost:"$0*"},
    Card{Id:162, Set: 7, Name: "Spoils", Type: "Treasure", Cost:"$0*"},
    Card{Id:163, Set: 7, Name: "Poor House", Type: "Action", Cost:"$1"},
    Card{Id:164, Set: 7, Name: "Beggar", Type: "Action &#8211; Reaction", Cost:"$2"},
    Card{Id:165, Set: 7, Name: "Squire", Type: "Action", Cost:"$2"},
    Card{Id:166, Set: 7, Name: "Vagrant", Type: "Action", Cost:"$2"},
    Card{Id:167, Set: 7, Name: "Forager", Type: "Action", Cost:"$3"},
    Card{Id:168, Set: 7, Name: "Hermit", Type: "Action", Cost:"$3"},
    Card{Id:169, Set: 7, Name: "Market Square", Type: "Action &#8211; Reaction", Cost:"$3"},
    Card{Id:170, Set: 7, Name: "Sage", Type: "Action", Cost:"$3"},
    Card{Id:171, Set: 7, Name: "Storeroom", Type: "Action", Cost:"$3"},
    Card{Id:172, Set: 7, Name: "Urchin", Type: "Action &#8211; Attack", Cost:"$3"},
    Card{Id:173, Set: 7, Name: "Armory", Type: "Action", Cost:"$4"},
    Card{Id:174, Set: 7, Name: "Death Cart", Type: "Action &#8211; Looter", Cost:"$4"},
    Card{Id:175, Set: 7, Name: "Feodum", Type: "Victory", Cost:"$4"},
    Card{Id:176, Set: 7, Name: "Fortress", Type: "Action", Cost:"$4"},
    Card{Id:177, Set: 7, Name: "Ironmonger", Type: "Action", Cost:"$4"},
    Card{Id:178, Set: 7, Name: "Marauder", Type: "Action &#8211; Attack &#8211; Looter", Cost:"$4"},
    Card{Id:179, Set: 7, Name: "Procession", Type: "Action", Cost:"$4"},
    Card{Id:180, Set: 7, Name: "Rats", Type: "Action", Cost:"$4"},
    Card{Id:181, Set: 7, Name: "Scavenger", Type: "Action", Cost:"$4"},
    Card{Id:182, Set: 7, Name: "Wandering Minstrel", Type: "Action", Cost:"$4"},
    Card{Id:183, Set: 7, Name: "Band of Misfits", Type: "Action", Cost:"$5"},
    Card{Id:184, Set: 7, Name: "Bandit Camp", Type: "Action", Cost:"$5"},
    Card{Id:185, Set: 7, Name: "Catacombs", Type: "Action", Cost:"$5"},
    Card{Id:186, Set: 7, Name: "Count", Type: "Action", Cost:"$5"},
    Card{Id:187, Set: 7, Name: "Counterfeit", Type: "Treasure", Cost:"$5"},
    Card{Id:188, Set: 7, Name: "Cultist", Type: "Action &#8211; Attack &#8211; Looter", Cost:"$5"},
    Card{Id:189, Set: 7, Name: "Graverobber", Type: "Action", Cost:"$5"},
    Card{Id:190, Set: 7, Name: "Junk Dealer", Type: "Action", Cost:"$5"},
    Card{Id:191, Set: 7, Name: "Mystic", Type: "Action", Cost:"$5"},
    Card{Id:192, Set: 7, Name: "Pillage", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:193, Set: 7, Name: "Rebuild", Type: "Action", Cost:"$5"},
    Card{Id:194, Set: 7, Name: "Rogue", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:195, Set: 7, Name: "Altar", Type: "Action", Cost:"$6"},
    Card{Id:196, Set: 7, Name: "Hunting Grounds", Type: "Action", Cost:"$6"},
    Card{Id:221, Set: 8, Name: "Candlestick Maker", Type: "Action", Cost:"$2"},
    Card{Id:222, Set: 8, Name: "Stonemason", Type: "Action", Cost:"$2+"},
    Card{Id:223, Set: 8, Name: "Doctor", Type: "Action", Cost:"$3+"},
    Card{Id:224, Set: 8, Name: "Masterpiece", Type: "Treasure", Cost:"$3+"},
    Card{Id:225, Set: 8, Name: "Advisor", Type: "Action", Cost:"$4"},
    Card{Id:226, Set: 8, Name: "Herald", Type: "Action", Cost:"$4+"},
    Card{Id:227, Set: 8, Name: "Plaza", Type: "Action", Cost:"$4"},
    Card{Id:228, Set: 8, Name: "Taxman", Type: "Action &#8211; Attack", Cost:"$4"},
    Card{Id:229, Set: 8, Name: "Baker", Type: "Action", Cost:"$5"},
    Card{Id:230, Set: 8, Name: "Butcher", Type: "Action", Cost:"$5"},
    Card{Id:231, Set: 8, Name: "Journeyman", Type: "Action", Cost:"$5"},
    Card{Id:232, Set: 8, Name: "Merchant Guild", Type: "Action", Cost:"$5"},
    Card{Id:233, Set: 8, Name: "Soothsayer", Type: "Action &#8211; Attack", Cost:"$5"},
    Card{Id:234, Set: 9, Name: "Black Market", Type: "Action", Cost:"$3"},
    Card{Id:235, Set: 9, Name: "Envoy", Type: "Action", Cost:"$4"},
    Card{Id:236, Set: 9, Name: "Walled Village", Type: "Action", Cost:"$4"},
    Card{Id:237, Set: 9, Name: "Governor", Type: "Action", Cost:"$5"},
    Card{Id:238, Set: 9, Name: "Stash", Type: "Treasure", Cost:"$5"},
  }
}

/* TODO

AllSets := []string{
  "Dominion", //0
  "Intrigue", // 1
  "Seaside", // 2
  "Alchemy", // 3
  "Prosperity", // 4
  "Cornucopia", // 5
  "Hinterlands", // 6
  "Dark Ages", // 7
  "Guilds", // 8
  "Promotional Cards", //9
}
*/